const categories = [
    {name: "خشکبار", slug: "dry-fruits", imageUrl: "/images/categories-real/dry-fruits.png"},
    {name: "نان محلی", slug: "local-bread", imageUrl: "/images/categories-real/local-bread.png"},
    {name: "عرقیجات گیاهی", slug: "herbal-distillates", imageUrl: "/images/categories-real/herbal-distillates.jpg"},
    {name: "زعفران", slug: "saffron", imageUrl: "/images/categories-real/saffron.png"},
    {name: "مربا و ترشی", slug: "jam-pickle", imageUrl: "/images/categories-real/jam-pickle.png"},
    {name: "لبنیات", slug: "dairy", imageUrl: "/images/categories-real/dairy.png"},
    {name: "عسل", slug: "honey", imageUrl: "/images/categories-real/honey.png"},
];

const products = [
    {
        name: "مربای به خانگی",
        slug: "quince-jam",
        description: "عطر دار و کم شکر.",
        price: 148000,
        stock: 40,
        imageUrl: "/images/products/jam.svg",
        category: "مربا و ترشی",
    },
    {
        name: "ترشی مخلوط",
        slug: "mixed-pickle",
        description: "ترکیب سبزیجات تازه.",
        price: 128000,
        stock: 32,
        imageUrl: "/images/products/jam.svg",
        category: "مربا و ترشی",
    },
    {
        name: "ماست محلی",
        slug: "local-yogurt",
        description: "طعم اصیل و بدون افزودنی.",
        price: 145000,
        stock: 28,
        imageUrl: "/images/products/yogurt.svg",
        category: "لبنیات",
    },
    {
        name: "عسل کوهستان",
        slug: "mountain-honey",
        description: "خالص و طبیعی.",
        price: 390000,
        stock: 18,
        imageUrl: "/images/products/honey.svg",
        category: "عسل",
    },
    {
        name: "تخم مرغ محلی",
        slug: "local-eggs",
        description: "تازه و روزانه.",
        price: 220000,
        stock: 20,
        imageUrl: "/images/products/eggs.svg",
        category: "لبنیات",
    },
    {
        name: "بادام درختی",
        slug: "almond",
        description: "خام ممتاز.",
        price: 420000,
        stock: 24,
        imageUrl: "/images/products/almond.svg",
        category: "خشکبار",
    },
    {
        name: "روغن زیتون",
        slug: "olive-oil",
        description: "فرابکر و طبیعی.",
        price: 310000,
        stock: 15,
        imageUrl: "/images/products/olive-oil.svg",
        category: "عسل",
    },
    {
        name: "خرما مضافتی",
        slug: "mazafati-date",
        description: "درجه یک بم.",
        price: 185000,
        stock: 26,
        imageUrl: "/images/products/date.svg",
        category: "عسل",
    },
    {
        name: "برنج قهوه ای",
        slug: "brown-rice",
        description: "سالم و ارگانیک.",
        price: 490000,
        stock: 12,
        imageUrl: "/images/products/brown-rice.svg",
        category: "خشکبار",
    },
    {
        name: "چای سبز",
        slug: "green-tea",
        description: "بدون افزودنی.",
        price: 195000,
        stock: 22,
        imageUrl: "/images/products/green-tea.svg",
        category: "عسل",
    },
    {
        name: "نان محلی سنگک",
        slug: "local-bread",
        description: "تنوری و تازه.",
        price: 68000,
        stock: 50,
        imageUrl: "/images/products/bread.svg",
        category: "نان محلی",
    },
    {
        name: "زعفران نگین",
        slug: "saffron",
        description: "مستقیم از کشاورز.",
        price: 520000,
        stock: 14,
        imageUrl: "/images/products/saffron.svg",
        category: "زعفران",
    },
    {
        name: "عرق نعناع",
        slug: "mint-distillate",
        description: "گیاهی و طبیعی.",
        price: 98000,
        stock: 30,
        imageUrl: "/images/products/distillate.svg",
        category: "عرقیجات گیاهی",
    },
];

module.exports = {categories, products};
